language: php
sudo: false
dist: trusty

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_FLAGS="--prefer-stable"

jobs:
  allow_failures:
    - php: nightly
  include:
    # SQLite
    - stage: Test
      php: 7.2
      env: DB="sqlite" PHPUNIT_CONF=".travis/phpunit.sqlite.xml" COMPOSER_FLAGS="--prefer-stable"
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      env: DB="sqlite" PHPUNIT_CONF=".travis/phpunit.sqlite.xml" COMPOSER_FLAGS="--prefer-stable"
    - stage: Test
      php: 7.4
      env: DB="sqlite" PHPUNIT_CONF=".travis/phpunit.sqlite.xml" COMPOSER_FLAGS="--prefer-stable"
    - stage: Test
      if: NOT type = pull_request
      php: nightly
      env: DB="sqlite" PHPUNIT_CONF=".travis/phpunit.sqlite.xml" COMPOSER_FLAGS="--prefer-stable --ignore-platform-req=php"

    # PDO MySQL 5.6
    - stage: Test
      php: 7.2
      env: DB="mysql" MYSQL_VERSION=5.6 PHPUNIT_CONF=".travis/phpunit.mysql.xml" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      env: DB="mysql" MYSQL_VERSION=5.6 PHPUNIT_CONF=".travis/phpunit.mysql.xml" COMPOSER_FLAGS="--prefer-stable"

    # PDO MySQL 5.7
    - stage: Test
      if: NOT type = pull_request
      php: 7.2
      env: DB="mysql.docker" MYSQL_VERSION=5.7 PHPUNIT_CONF=".travis/phpunit.mysql.docker.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mysql-5.7.sh
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      env: DB="mysql.docker" MYSQL_VERSION=5.7 PHPUNIT_CONF=".travis/phpunit.mysql.docker.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mysql-5.7.sh
    - stage: Test
      php: 7.4
      env: DB="mysql.docker" MYSQL_VERSION=5.7 PHPUNIT_CONF=".travis/phpunit.mysql.docker.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mysql-5.7.sh
    - stage: Test
      if: NOT type = pull_request
      php: nightly
      env: DB="mysql.docker" MYSQL_VERSION=5.7 PHPUNIT_CONF=".travis/phpunit.mysql.docker.xml" COMPOSER_FLAGS="--prefer-stable --ignore-platform-req=php"
      before_script:
        - bash ./.travis/install-mysql-5.7.sh

    # PDO MySQL 8.0
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      env: DB="mysql.docker" MYSQL_VERSION=8.0 PHPUNIT_CONF=".travis/phpunit.mysql.docker.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mysql-8.0.sh
    - stage: Test
      php: 7.4
      env: DB="mysql.docker" MYSQL_VERSION=8.0 PHPUNIT_CONF=".travis/phpunit.mysql.docker.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mysql-8.0.sh
    - stage: Test
      if: NOT type = pull_request
      php: nightly
      env: DB="mysql.docker" MYSQL_VERSION=8.0 PHPUNIT_CONF=".travis/phpunit.mysql.docker.xml" COMPOSER_FLAGS="--prefer-stable --ignore-platform-req=php"
      before_script:
        - bash ./.travis/install-mysql-8.0.sh

    # MySQLi 5.6
    - stage: Test
      php: 7.2
      env: DB="mysqli" MYSQL_VERSION=5.6 PHPUNIT_CONF=".travis/phpunit.mysqli.xml" COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      env: DB="mysqli" MYSQL_VERSION=5.6 PHPUNIT_CONF=".travis/phpunit.mysqli.xml" COMPOSER_FLAGS="--prefer-stable"

    # MySQLi 5.7
    - stage: Test
      if: NOT type = pull_request
      php: 7.2
      env: DB="mysqli.docker" MYSQL_VERSION=5.7 PHPUNIT_CONF=".travis/phpunit.mysqli.docker.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mysql-5.7.sh
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      env: DB="mysqli.docker" MYSQL_VERSION=5.7 PHPUNIT_CONF=".travis/phpunit.mysqli.docker.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mysql-5.7.sh
    - stage: Test
      php: 7.4
      env: DB="mysqli.docker" MYSQL_VERSION=5.7 PHPUNIT_CONF=".travis/phpunit.mysqli.docker.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mysql-5.7.sh
    - stage: Test
      if: NOT type = pull_request
      php: nightly
      env: DB="mysqli.docker" MYSQL_VERSION=5.7 PHPUNIT_CONF=".travis/phpunit.mysqli.docker.xml" COMPOSER_FLAGS="--prefer-stable --ignore-platform-req=php"
      before_script:
        - bash ./.travis/install-mysql-5.7.sh

    # MySQLi 8.0
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      env: DB="mysqli.docker" MYSQL_VERSION=8.0 PHPUNIT_CONF=".travis/phpunit.mysqli.docker.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mysql-8.0.sh
    - stage: Test
      php: 7.4
      env: DB="mysqli.docker" MYSQL_VERSION=8.0 PHPUNIT_CONF=".travis/phpunit.mysqli.docker.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mysql-8.0.sh
    - stage: Test
      if: NOT type = pull_request
      php: nightly
      env: DB="mysqli.docker" MYSQL_VERSION=8.0 PHPUNIT_CONF=".travis/phpunit.mysqli.docker.xml" COMPOSER_FLAGS="--prefer-stable --ignore-platform-req=php"
      before_script:
        - bash ./.travis/install-mysql-8.0.sh

    # MariaDB 10.0 (MySQLi)
    - stage: Test
      php: 7.2
      dist: precise
      addons:
        mariadb: 10.0
      env: DB="mariadb" MARIADB_VERSION=10.0 PHPUNIT_CONF=".travis/phpunit.mysqli.xml" COMPOSER_FLAGS="--prefer-stable"

    # MariaDB 10.1 (MySQLi)
    - stage: Test
      if: NOT type = pull_request
      php: 7.2
      addons:
        mariadb: 10.1
      env: DB="mariadb" MARIADB_VERSION=10.1 PHPUNIT_CONF=".travis/phpunit.mysqli.xml" COMPOSER_FLAGS="--prefer-stable"

    # MariaDB 10.2 (MySQLi)
    - stage: Test
      if: NOT type = pull_request
      php: 7.2
      addons:
        mariadb: 10.2
      env: DB="mariadb" MARIADB_VERSION=10.2 PHPUNIT_CONF=".travis/phpunit.mysqli.xml" COMPOSER_FLAGS="--prefer-stable"
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      addons:
        mariadb: 10.2
      env: DB="mariadb" MARIADB_VERSION=10.2 PHPUNIT_CONF=".travis/phpunit.mysqli.xml" COMPOSER_FLAGS="--prefer-stable"
    - stage: Test
      php: 7.4
      addons:
        mariadb: 10.2
      env: DB="mariadb" MARIADB_VERSION=10.2 PHPUNIT_CONF=".travis/phpunit.mysqli.xml" COMPOSER_FLAGS="--prefer-stable"
    - stage: Test
      if: NOT type = pull_request
      php: nightly
      addons:
        mariadb: 10.2
      env: DB="mariadb" MARIADB_VERSION=10.2 PHPUNIT_CONF=".travis/phpunit.mysqli.xml" COMPOSER_FLAGS="--prefer-stable --ignore-platform-req=php"

    # MariaDB 10.0 (PDO MySQL)
    - stage: Test
      php: 7.2
      addons:
        mariadb: 10.0
      env: DB="mariadb" MARIADB_VERSION=10.0 PHPUNIT_CONF=".travis/phpunit.mysql.xml" COMPOSER_FLAGS="--prefer-stable"

    # MariaDB 10.1 (PDO MySQL)
    - stage: Test
      if: NOT type = pull_request
      php: 7.2
      addons:
        mariadb: 10.1
      env: DB="mariadb" MARIADB_VERSION=10.1 PHPUNIT_CONF=".travis/phpunit.mysql.xml" COMPOSER_FLAGS="--prefer-stable"

    # MariaDB 10.2 (PDO MySQL)
    - stage: Test
      if: NOT type = pull_request
      php: 7.2
      addons:
        mariadb: 10.2
      env: DB="mariadb" MARIADB_VERSION=10.2 PHPUNIT_CONF=".travis/phpunit.mysql.xml" COMPOSER_FLAGS="--prefer-stable"
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      addons:
        mariadb: 10.2
      env: DB="mariadb" MARIADB_VERSION=10.2 PHPUNIT_CONF=".travis/phpunit.mysql.xml" COMPOSER_FLAGS="--prefer-stable"
    - stage: Test
      php: 7.4
      addons:
        mariadb: 10.2
      env: DB="mariadb" MARIADB_VERSION=10.2 PHPUNIT_CONF=".travis/phpunit.mysql.xml" COMPOSER_FLAGS="--prefer-stable"
    - stage: Test
      if: NOT type = pull_request
      php: nightly
      addons:
        mariadb: 10.2
      env: DB="mariadb" MARIADB_VERSION=10.2 PHPUNIT_CONF=".travis/phpunit.mysql.xml" COMPOSER_FLAGS="--prefer-stable --ignore-platform-req=php"

    # PDO PostgreSQL 9.4
    - stage: Test
      php: 7.2
      addons:
        postgresql: "9.4"
      services:
        - postgresql
      env: DB="pgsql" PGSQL_VERSION=9.4 PHPUNIT_CONF=".travis/phpunit.pgsql.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - psql -U postgres -c 'create database joomla_ut;'
        - psql -U postgres -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql

    # PDO PostgreSQL 9.5
    - stage: Test
      if: NOT type = pull_request
      php: 7.2
      addons:
        postgresql: "9.5"
      services:
        - postgresql
      env: DB="pgsql" PGSQL_VERSION=9.5 PHPUNIT_CONF=".travis/phpunit.pgsql.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - psql -U postgres -c 'create database joomla_ut;'
        - psql -U postgres -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql

    # PDO PostgreSQL 9.6
    - stage: Test
      php: 7.3
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      env: DB="pgsql" PGSQL_VERSION=9.6 PHPUNIT_CONF=".travis/phpunit.pgsql.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - psql -U postgres -c 'create database joomla_ut;'
        - psql -U postgres -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql

    # PDO PostgreSQL 10.0
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      env: DB="pgsql" PGSQL_VERSION=10.0 PHPUNIT_CONF=".travis/phpunit.pgsql.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-postgres-10.sh
        - psql -U postgres -c 'create database joomla_ut;'
        - psql -U postgres -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql
    - stage: Test
      php: 7.4
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      env: DB="pgsql" PGSQL_VERSION=10.0 PHPUNIT_CONF=".travis/phpunit.pgsql.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-postgres-10.sh
        - psql -U postgres -c 'create database joomla_ut;'
        - psql -U postgres -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql
    - stage: Test
      if: NOT type = pull_request
      php: nightly
      addons:
        postgresql: "9.6"
      services:
        - postgresql
      env: DB="pgsql" PGSQL_VERSION=10.0 PHPUNIT_CONF=".travis/phpunit.pgsql.xml" COMPOSER_FLAGS="--prefer-stable --ignore-platform-req=php"
      before_script:
        - bash ./.travis/install-postgres-10.sh
        - psql -U postgres -c 'create database joomla_ut;'
        - psql -U postgres -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql

    # PDO PostgreSQL 11.0
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      services:
        - docker
      env: DB="pgsql" PGSQL_VERSION=11.0 PHPUNIT_CONF=".travis/phpunit.pgsql.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-postgres-11.sh
        - psql -U postgres -h localhost -c 'create database joomla_ut;'
        - psql -U postgres -h localhost -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql
    - stage: Test
      php: 7.4
      services:
        - docker
      env: DB="pgsql" PGSQL_VERSION=11.0 PHPUNIT_CONF=".travis/phpunit.pgsql.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-postgres-11.sh
        - psql -U postgres -h localhost -c 'create database joomla_ut;'
        - psql -U postgres -h localhost -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql
    - stage: Test
      if: NOT type = pull_request
      php: nightly
      services:
        - docker
      env: DB="pgsql" PGSQL_VERSION=11.0 PHPUNIT_CONF=".travis/phpunit.pgsql.xml" COMPOSER_FLAGS="--prefer-stable --ignore-platform-req=php"
      before_script:
        - bash ./.travis/install-postgres-11.sh
        - psql -U postgres -h localhost -c 'create database joomla_ut;'
        - psql -U postgres -h localhost -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql

    # SQL Server
    - stage: Test
      php: 7.2
      sudo: required
      services:
        - docker
      env: DB="sqlsrv" SQL_SERVER_VERSION="5.8.0" PHPUNIT_CONF=".travis/phpunit.sqlsrv.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mssql.sh $SQL_SERVER_VERSION
    - stage: Test
      if: NOT type = pull_request
      php: 7.3
      sudo: required
      services:
        - docker
      env: DB="sqlsrv" SQL_SERVER_VERSION="5.8.0" PHPUNIT_CONF=".travis/phpunit.sqlsrv.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mssql.sh $SQL_SERVER_VERSION
    - stage: Test
      php: 7.4
      sudo: required
      services:
        - docker
      env: DB="sqlsrv" SQL_SERVER_VERSION="5.8.0" PHPUNIT_CONF=".travis/phpunit.sqlsrv.xml" COMPOSER_FLAGS="--prefer-stable"
      before_script:
        - bash ./.travis/install-mssql.sh $SQL_SERVER_VERSION
    - stage: Test
      if: NOT type = pull_request
      php: nightly
      sudo: required
      services:
        - docker
      env: DB="sqlsrv" SQL_SERVER_VERSION="5.8.0" PHPUNIT_CONF=".travis/phpunit.sqlsrv.xml" COMPOSER_FLAGS="--prefer-stable --ignore-platform-req=php"
      before_script:
        - bash ./.travis/install-mssql.sh $SQL_SERVER_VERSION

    # PHPCS
    - stage: Coding standard
      php: 7.2
      script:
        - vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards && vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/

install:
  - rm -f composer.lock
  - travis_retry composer -n update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --configuration $PHPUNIT_CONF
